import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import ThemeToggle from "./components/Theme";


const poppins = Poppins ({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: "Prama | Portofolio",
  description: "Generated by create next app",
  
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} bg-gray-50 dark:bg-zinc-900`}
      >
        
        <ThemeToggle>
        {children}
        </ThemeToggle>
      </body>
    </html>
  );
}
